apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflow
rules:
  - apiGroups: [""]
    resources:
      - pods
      - pods/log
      - pods/status
      - configmaps
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["argoproj.io"]
    resources:
      - workflows
      - workflows/status
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
    #Comentario
