apiVersion: v1
kind: Service
metadata:
  name: argo-server
  namespace: argo
spec:
  type: ClusterIP  # Configurado como ClusterIP
  ports:
    - name: web
      port: 2746
      protocol: TCP
      targetPort: 2746
  selector:
    app: argo-server
