apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: argo-events
spec:
  nats:
    native:
      replicas: 3
      config: |
        cluster {
          name: "eventbus-cluster"  # Nombre de cluster fijo
          listen: 0.0.0.0:6222
        }
        server_name: "eventbus-default-stan"
        store {
          type: "file"
          file {
            directory: "/data/stan/store"
          }
        }

