apiVersion: v1
kind: Service
metadata:
  name: github-eventsource-svc
  namespace: argo-events
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: argo-events-controller-manager
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: argo-events
  ports:
    - port: 12000
      targetPort: 12000
      protocol: TCP
      nodePort: 31234

