apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github-eventsource
  namespace: argo-events
spec:
  github:
    example:
      apiToken:
        name: github-token
        key: token
      events:
        - push
      repositories:
        - owner: MiltonRPG
          repo: proyecto-cicd
      webhook:
        endpoint: /webhook
        method: POST
        port: 12000

