apiVersion: v1
kind: Service
metadata:
  name: github-eventsource-svc
  namespace: argo-events
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: argo-events-controller-manager
    app.kubernetes.io/component: controller-manager
  ports:
    - port: 7777
      targetPort: 7777
      protocol: TCP
      nodePort: 31234  # Ajusta si ya está en uso
