apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: github-dep
      eventSourceName: github-eventsource
      eventName: example
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: proyecto-cicd-
              spec:
                entrypoint: cicd-pipeline
                serviceAccountName: argo-workflow
                templates:
    - name: cicd-pipeline
      dag:
        tasks:
          - name: clone-repo
            template: clone-repo

          - name: build-image
            dependencies: [clone-repo]
            template: build-image
            arguments:
              artifacts:
                - name: source-code
                  from: "{{tasks.clone-repo.outputs.artifacts.source-code}}"

          - name: run-tests
            dependencies: [build-image]
            template: run-tests
            arguments:
              artifacts:
                - name: source-code
                  from: "{{tasks.clone-repo.outputs.artifacts.source-code}}"

          - name: lint
            dependencies: [build-image]
            template: lint
            arguments:
              artifacts:
                - name: source-code
                  from: "{{tasks.clone-repo.outputs.artifacts.source-code}}"

          - name: deploy
            dependencies: [run-tests, lint]
            template: deploy
            arguments:
              artifacts:
                - name: source-code
                  from: "{{tasks.clone-repo.outputs.artifacts.source-code}}"
              podGC:
                  strategy: OnWorkflowSuccess
