# PersistentVolume y PersistentVolumeClaim para almacenamiento persistente
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: argo-events
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"  # Cambia esto a una ruta válida en tu nodo

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: argo-events
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
# MinIO Service
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: argo-events
  labels:
    app: minio
spec:
  ports:
    - port: 9000
      targetPort: 9000
  selector:
    app: minio
  type: ClusterIP

---
# MinIO Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: argo-events
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          args:
            - server
            - /data
          env:
            - name: MINIO_ROOT_USER
              value: minio
            - name: MINIO_ROOT_PASSWORD
              value: minio123
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio-pvc



